name: PR ADR Validation Workflow

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Parse PR label and title
        uses: actions/github-script@v6
        id: lint_title_adr
        with:
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.pull_request.title;
            const labels = context.payload.pull_request.labels;
            const hasAdrLabel = labels.some(label => label.name === 'kind/adr');
            const re = /^chore:\s*\[ADR-\d{4}\]/;
            const startsWithAdr = (title.match(re) !== null);
            console.log(`title : ${title} - labels: ${labels} - hasAdrLabel: ${hasAdrLabel} - startsWithAdr: ${startsWithAdr}`);
            if (hasAdrLabel && !startsWithAdr) {
              return "The PR Title must starts with `chore: [ADR-nnnn] name of ADR` where `nnnn` is the adr number (e.g `chore: [ADR-0001] use architecture decision records`) same us commits"
            }
            if (!hasAdrLabel && startsWithAdr) {
              return "This PR must have kind/adr label"
            }
            return ''
      - name: Check PR label and title
        uses: actions/github-script@v6
        id: lint_title_adr_check
        with:
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (${{ steps.lint_title_adr.outputs.result != '' }}) {
              throw new Error(${{ steps.lint_title_adr.outputs.result }})
            }
      - if: always() && steps.lint_title_adr.outputs.result != ''
        uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        with:
          header: pr-title-lint-adr-error
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          message: |
            Hey there and thank you for opening this ADR pull request! ðŸ‘‹ðŸ¼
            The ADR Pull request must follow this PR naming convention: 
            ```
            ${{ steps.lint_title_adr.outputs.result }}
            ```
      # Delete a previous comment when the issue has been resolved
      - if: steps.lint_title_adr.outputs.result == ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          header: pr-title-lint-adr-error
          delete: true
      # Check commit changes
      - name: Check Commit Changes
        uses: actions/github-script@v6
        with:
          result-encoding: json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(github.event.commits);
            const commits = context.payload.event.commits;

            const commitFiles = commits.data[0].files.map(file => file.filename);
            console.log('Commit Files:', commitFiles);

            const isDocAdrFile = commitFiles.every(file => file.startsWith('doc/adr/'));
            console.log('Is Doc ADR File:', isDocAdrFile);
            if (!isDocAdrFile) {
              throw new Error('Commit changes must only concern files starting with doc/adr/');
            }
            